name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  push:

env:
  DOCKER-CONTEXT: ./
  DOCKER-FILE: ./.github/Dockerfile

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKER-CONTEXT }}
          file: ${{ env.DOCKER-FILE }}
          tags: ghcr.io/${{ github.repository_owner }}/ike_nav:$ROS_DISTRO
          build-args: USERNAME=$USER
          no-cache: true
          push: true
